### ISSUE TITLE
Task #91 for HolographicScoreboard v1.3.8 generated an exception

### ISSUE THREAD

**Issue by k3ldon** [rlf/Holographic-Scoreboard#15]
i have that error all time, someone know how to fix?

[15:08:13] [Server thread/WARN]: [HolographicScoreboard] Task #91 for HolographicScoreboard v1.3.8 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'inspect' in plugin mcMMO v1.5.01-SNAPSHOT-b3710
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:575) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at dk.lockfuglsang.wolfencraft.config.Scoreboard.refreshView(Scoreboard.java:103) ~[?:?]
	at dk.lockfuglsang.wolfencraft.HolographicScoreboard$1.run(HolographicScoreboard.java:108) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.database.SQLDatabaseManager.getUserID(SQLDatabaseManager.java:1564) ~[?:?]
	at com.gmail.nossr50.database.SQLDatabaseManager.loadPlayerProfile(SQLDatabaseManager.java:621) ~[?:?]
	at com.gmail.nossr50.database.SQLDatabaseManager.loadPlayerProfile(SQLDatabaseManager.java:603) ~[?:?]
	at com.gmail.nossr50.commands.player.InspectCommand.onCommand(InspectCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	... 12 more
[15:02:21] [Server thread/WARN]: [HolographicScoreboard] Task #101 for HolographicScoreboard v1.3.8 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'inspect' in plugin mcMMO v1.5.01-SNAPSHOT-b3710
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:575) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at dk.lockfuglsang.wolfencraft.config.Scoreboard.refreshView(Scoreboard.java:103) ~[?:?]
	at dk.lockfuglsang.wolfencraft.HolographicScoreboard$1.run(HolographicScoreboard.java:108) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.database.SQLDatabaseManager.getUserID(SQLDatabaseManager.java:1564) ~[?:?]
	at com.gmail.nossr50.database.SQLDatabaseManager.loadPlayerProfile(SQLDatabaseManager.java:621) ~[?:?]
	at com.gmail.nossr50.database.SQLDatabaseManager.loadPlayerProfile(SQLDatabaseManager.java:603) ~[?:?]
	at com.gmail.nossr50.commands.player.InspectCommand.onCommand(InspectCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
	... 12 more

**Comment by rlf** [comment]
The `/inspect` command in your HGS is trying to run as a player command, and is throwing this error.
